CampOasis/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from CampOasis import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
    url(r'^booking/', include('booking.urls', namespace='booking')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    # url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^$', views.login_redirect, name='login_redirect'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(url(r'^debug/', include(debug_toolbar.urls)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login, logout

# Add Django site authentication urls (for login, logout, password management)
urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^$', views.home, name='home'),
    # contact url
    url(r'^contact/$', views.contact, name='contact'),
]

cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class UserProfile(models.Model):
    user = models.ForeignKey(User)
    gender = models.CharField(max_length=10, verbose_name='Gender', default='Male')
    organisation = models.CharField(max_length=20, verbose_name='Organisation', default="")
    phone = models.IntegerField(default=0)

    def __str__(self):
        return self.user.email

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import (
    UserCreationForm,
    UserChangeForm,
)
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    password1 = forms.CharField(
        label='Password',
        widget=forms.PasswordInput
    )

    password2 = forms.CharField(
        label='Password Confirmation',
        widget=forms.PasswordInput
    )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2']
        exclude = ['username']

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            message = "Passwords do not match"
            raise ValidationError(message)

        return password2

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        user.username = user.email

        if commit:
            user.save()

        return user

class UserLoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'password')

class ContactForm(forms.Form):
    contact_name = forms.CharField(required=True)
    contact_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(
        required=True,
        widget=forms.Textarea
    )

accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib import messages, auth
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
from django.template.context_processors import csrf
from accounts.forms import (
    UserRegistrationForm,
    EditProfileForm,
    UserLoginForm,
    ContactForm,
)

def home(request):
    return render(request, 'home.html')

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()

            user = auth.authenticate(email=request.POST.get('email'))

            if user:
                messages.success(request, "You have successfully registered")
                return redirect(reverse('/account'))

            else:
                messages.error(request, "unable to log you in at this time!")

    else:
        form = UserRegistrationForm()

    args = {'form': form}
    args.update(csrf(request))

    return render(request, 'accounts/register.html', args)

def login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST or None)
        if form.is_valid():
            user = auth.authenticate(email=request.POST.get('email'), password=request.POST.get('password'))

            if user is not None:
                auth.login(request, user)
                messages.error(request, "You have successfully logged in")
                return redirect(reverse('profile'))
            else:
                form.add_error(None, "Your email or password was not recognised")
    else:
        form = UserLoginForm()

    args = {'form': form}
    args.update(csrf(request))
    return render(request, 'accounts/login.html', args)

def profile(request):
    args = {'user': request.user}
    return render(request, 'accounts/profile.html', args)

def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('/accounts/profile')
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)

def logout(request):
    auth.logout(request)
    messages.success(request, 'You have successfully logged out')
    return redirect(reverse('home'))

def contact(request):
    form_class = ContactForm

    return render(request, 'contact.html', {
        'form': form_class,
    })

templates/accounts/contact.html
{% extends 'base.html' %}
{% block title %}Contact - {{ block.super }}{% endblock %}

{% block content %}
<h1>Contact</h1>
<form role="form" action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
<div class="container">
    <div class="social-links">
    <div class="row">
        <h5>CONNECT</h5>
				<ul class ="social social-link">
					<li>
                        <a href="http://www.facebook.com/campoasis" title="Facebook" class="icon-circle icon-circle--white">
                            <i class="icon icon-facebook" aria-hidden="true"></i><span class="facebook">Facebook</span></a>
                    </li>
					<li>
                        <a href="http://www.twitter.com/campoasis" title="Twitter" class="icon-circle icon-circle--white">
                            <i class="icon icon-twitter" aria-hidden="true"></i><span class="vh">Twitter</span></a>
                    </li>

					<li>
                        <a href="http://www.youtube.com/user/campoasis" title="YouTube" class="icon-circle icon-circle--white">
                            <i class="icon icon-youtube" aria-hidden="true"></i><span class="vh">YouTube</span></a>
                    </li>

					<li>
                        <a href="https://instagram.com/campoasis" title="Instagram" class="icon-circle icon-circle--white">
                            <i class="icon icon-instagram" aria-hidden="true"></i><span class="vh">Instagram</span></a>
                    </li>
					<li>
                        <a href="https://plus.google.com/+universitynorthampton/posts" title="Google Plus" class="icon-circle icon-circle--white">
                            <i class="icon icon-googleplus" aria-hidden="true"></i><span class="vh">Google Plus</span></a>
                    </li>
				</ul>
			</div>

			<div class="col-sm-6">
				<h5>SUBSCRIBE</h5>
					<form action="#">
						<div class="form-group">
							<input type="text" class="btn btn-md" name="email" id="email" placeholder="Your Email" required>
							<button class="btn btn-primary btn-md" type="submit">Submit</button>
						</div>
					</form>
			</div>
		</div>
    </div>
{% endblock %}

templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Edit Profile</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</div>
{% endblock %}

templates/accounts/login.html
{% extends "base.html" %}
{% block content %}
    <h2>Login</h2>
    <div class="container">
        <p>You can login here!</p>
        <form role="form" method="post" action="{% url 'accounts:login' %}">
            {% csrf_token %}
            {{ form.as_p}}
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>
{% endblock %}

templates/accounts/logout.html
{%  extends 'base.html' %}
{% block body%}
    <div class="container">
        <h2>Logged out</h2><br>
            <p>You have logged out.</p>
    </div>
{% endblock %}

templates/accounts/profile.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h2>Profile</h2>
    <p>You are logged in as {{ user.email }} </p>
</div>
{% endblock %}

templates/accounts/register.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
  <form role="form" method="post" id="register-form" action="{% url 'accounts:register' %}">
    <legend>Register</legend>
    {% csrf_token %}
    {{ form.as_p}}
    <div class="form-group">
      <input class="btn btn-primary" id="validate_card_btn" name="commit" type="submit" value="Register">
    </div>
  </form>
</div>
{% endblock %}

templates/accounts/view_profile.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h2>Profile</h2>
    <p>You are logged in as {{ user.email }} </p>
</div>
{% endblock %}